export type Films = {
  id: number;
  title: string;
  rating?: string;
  imgUrl: string;
  status?: string;
  category: string;
};

export const dataFilm: Films[] = [
  {
    id: 1,
    title: "Duty After School",
    rating: "4.5/5",
    imgUrl: "/images/dontLookUp.png",
    status: "",
    category: "nextFilm",
  },
  {
    id: 2,
    title: "The Batman",
    rating: "4.2/5",
    imgUrl: "/images/theBatman.png",
    status: "",
    category: "nextFilm",
  },
  {
    id: 3,
    title: "Blue Lock",
    rating: "4.6/5",
    imgUrl: "/images/blueLock.png",
    status: "",
    category: "nextFilm",
  },
  {
    id: 4,
    title: "A Man Called Otto",
    rating: "4.4/5",
    imgUrl: "/images/aManCalledOtto.png",
    status: "",
    category: "nextFilm",
  },
  {
    id: 5,
    title: "Suzume",
    rating: "4.8/5",
    imgUrl: "/images/suzume.png",
    status: "new",
    category: "topRating",
  },
  {
    id: 6,
    title: "Jurassic World",
    rating: "4.7/5",
    imgUrl: "/images/jurassicWorld.png",
    status: "old",
    category: "topRating",
  },
  {
    id: 7,
    title: "Sonic The Hedgehog",
    rating: "4.3/5",
    imgUrl: "/images/sonic.png",
    status: "old",
    category: "topRating",
  },
  {
    id: 8,
    title: "The Batman",
    rating: "4.1/5",
    imgUrl: "/images/TheBatmanPotrait.png",
    status: "old",
    category: "topRating",
  },
  {
    id: 9,
    title: "Big Hero 6",
    rating: "4.5/5",
    imgUrl: "/images/bigHero.png",
    status: "top",
    category: "topRating",
  },
  {
    id: 10,
    title: "The Tomorrow War",
    rating: "4.5/5",
    imgUrl: "/images/theTomorrow.png",
    status: "top",
    category: "trending",
  },
  {
    id: 11,
    title: "Quantumania",
    rating: "4.5/5",
    imgUrl: "/images/quantumania.png",
    status: "top",
    category: "trending",
  },
  {
    id: 12,
    title: "Guardians of the Galaxy",
    rating: "4.5/5",
    imgUrl: "/images/guardians.png",
    status: "top",
    category: "trending",
  },
  {
    id: 13,
    title: "A Man Called Otto",
    rating: "4.5/5",
    imgUrl: "/images/aManCalledOttoPotrait.png",
    status: "top",
    category: "trending",
  },
  {
    id: 14,
    title: "Little Mermaid",
    rating: "4.5/5",
    imgUrl: "/images/littleMermaid.png",
    status: "top",
    category: "trending",
  },
  {
    id: 15,
    title: "Little Mermaid",
    rating: "4.5/5",
    imgUrl: "/images/littleMermaid.png",
    status: "top",
    category: "newRelease",
  },
  {
    id: 16,
    title: "Duty After School",
    rating: "4.5/5",
    imgUrl: "/images/dutyAfterSchool.png",
    status: "new",
    category: "newRelease",
  },
  {
    id: 17,
    title: "Big Hero 6",
    rating: "4.5/5",
    imgUrl: "/images/bigHero.png",
    status: "top",
    category: "newRelease",
  },
  {
    id: 18,
    title: "The Batman",
    rating: "4.5/5",
    imgUrl: "/images/TheBatmanPotrait.png",
    status: "new",
    category: "newRelease",
  },
  {
    id: 19,
    title: "Missing",
    rating: "4.5/5",
    imgUrl: "/images/missing.png",
    status: "",
    category: "newRelease",
  },
];
